config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users

  resources :users do
    get 'my_address', :to => 'users#my_address', as: 'address'
    post 'my_address', :to => 'users#my_address', as: 'assign_new_address'
  end

  post 'address/:user_id/generate', :to => 'address#generate_new'
end

app/models/address.rb
class Address < ApplicationRecord
  has_one :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jwt_blacklist.rb
class JWTBlacklist < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Blacklist

  self.table_name = 'jwt_blacklist'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :jwt_authenticatable,
         jwt_revocation_strategy: JWTBlacklist

  belongs_to :address, optional: true
end

app/controllers/address_controller.rb
class AddressController < ActionController::API
  before_action :authenticate_user!
  respond_to :json

  def initialize
    @address_service = AddressService.new
    super
  end

  def generate_new
    @user = User.find(params[:user_id])

    if @user == current_user
      address = @address_service.address_from_pool
      if address
        @user.update(address: address)
        render json: address
      else
        bad_request 'Address Pool empty, please try again in 12 Minutes'
      end
    else
      access_denied
    end
  end

  def bad_request(message)
    render json: { error: message }, status: :bad_request
  end

  def access_denied
    render json: { error: 'Access denied.' }, status: :forbidden
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token

  def after_sign_in_path_for(resource)
    if resource.is_a?(User)
      "/users/#{resource.id}/my_address"
    else
      super
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def initialize
    @address_service = AddressService.new
    super
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_path, alert: 'Access denied.' if @user != current_user
  end

  def my_address
    @user = User.find(params[:user_id])

    if params[:assign_new]
      @user.update(address: @address_service.address_from_pool) if @user == current_user
    elsif @user == current_user && !@user.address
      @user.update(address: @address_service.address_from_pool)
    end
    redirect_to root_path, alert: 'Access denied.' if @user != current_user
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'My Address', user_address_path(user_id: current_user.id) %></li>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Test App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Test App" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Test Task</h3>
<pre>
  Project:
  Use devise to create a simple authentication process (use of default devise templates allowed).
  A user should not have to confirm his email address. He will be allowed to login right after
  signup. After login, the user should get redirected to "/my_address". On view, a new address is
  assigned to the user. A button gives the possibility to assign a new address from the address
  pool to the user.
  Definitions:
  Address: Random 34 characters, digits, uppercase, lowercase. Uppercase letter "O",
  uppercase letter "I", lowercase letter "l", and the number "0" are excluded!
  Address Pool: Holds 10 addresses, generates new addresses through cronjob (use gem)
  every 12 minutes.
  Features:
  - If the address pool runs out of addresses and the user tries to generate a new one, a
  message should be shown: "Address Pool empty, please try again in x Minutes" where x
  is the value of the remaining time when the cronjob will run again.
  - Integrate a JWT authentication so that a user can view and generate a new address via
  API.
  - Write a short description how to call the api endpoint.
</pre>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/my_address.html.erb
<% content_for :title do %>My address
<% end %>
<div class="container">
  <div class="row">
    <h3>My address</h3>
  </div>
  <div class="row">
    <div class="col-md-6">
      <p>Location: <%= @user.address.location if @user.address %></p>
    </div>
    <div class="col-md-6">
      <%= button_to "Assign new Address", user_assign_new_address_path(user_id: current_user.id, assign_new: true), :data => {:confirm => "Are you sure?"}, :method => :post, :class => 'btn btn-success pull-right' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>